### ISSUE TITLE
NeuroHub bugs checklist

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#921]
Enter NeuroHub bugs/limitations below as a checklist. Checkboxes are created with dash, space, square bracket, space, square bracket, space (- [ ] Text).

- [ ] When account is created, the user is redirected to cbrain with no way of signing in to NeuroHub.
- [ ] Pagination defaults to 20 even if there are less than 20 items.
- [ ] In the upload file form, if the user doesn't fill in a required input, he/she is only notified of the error through flash notice after being redirected to the projects page. It would be nice to have a warning when there's missing information much like with the user register form.
- [ ] Check that all cbrain links are external and open in new tab. (I already checked but would like someone to double check if they have time in case I missed any. - Candice)
- [x] user should be able only add storage to a project if he is editor or maintainer at the least, remove irrelevant projects from the create new storage forms' project dropdown. IF I am wrong and it is fine for any contributor to add projects storage, put back the add storage button to non-editable projects. (Natacha note: I am able to add a DP to a PUBLIC project via CBRAIN, when I use a user (SiteManager) that is a member of this group but not an Editor. I should not be able to do that.)
- [x] If an Editor of a public project has the same right than the creator then it should be able to add a licence to the group. It is not the case for the moment. @prioux can you confirm that an editor should have this ability. 

--------------------------------------------------------
For the list of bugs resolved by April 7 click [here](https://github.com/aces/cbrain/issues/921#issuecomment-610424204)
For the list of bugs resolved by April 15 click [here](https://github.com/aces/cbrain/issues/921#issuecomment-614157355)
For the list of bugs resolved by April 16 click [here](https://github.com/aces/cbrain/issues/921#issuecomment-614682392)
For the list of bugs resolved by April 20 click [here](https://github.com/aces/cbrain/issues/921#issuecomment-616731332)
For the list of bugs resolved by April 22 click [here](https://github.com/aces/cbrain/issues/921#issuecomment-617980477)
For the list of bugs resolved by April 29 click [here](https://github.com/aces/cbrain/issues/921#issuecomment-621251758)

**Comment by MontrealSergiy** [comment]
@prioux Should I add a Project link to My Account or @candicecz to the menu bar?

**Comment by prioux** [comment]
Added a bug in project show page

**Comment by natacha-beck** [comment]
Added 2 new bugs.

**Comment by emmetaobrien** [comment]
- [ ] In the "NeuroHub Architectural Components" section on https://neurohub.ca/vision.html we still list the OSF portal as our candidate technology for the portal space.

**Comment by adora07** [comment]
> * [ ]  In the "NeuroHub Architectural Components" section on https://neurohub.ca/vision.html we still list the OSF portal as our candidate technology for the portal space.

@emmetaobrien can you log this issue? would like JB to ok the removal of this.

**Comment by emmetaobrien** [comment]
@adora07: I had thought here was the appropriate place for noting things of this scale; where should I log that?

**Comment by adora07** [comment]
for the https://neurohub.ca website (not portal), log issues here: https://github.com/neurohub/neurohub.github.io/issues

**Comment by emmetaobrien** [comment]
Checking in there, my comment turns out to be a duplicate of https://github.com/neurohub/neurohub.github.io/issues/3

**Comment by prioux** [comment]
@candicecz Added an issue for you in the check list above.

**Comment by prioux** [comment]
@candicecz Added one more feature request

**Comment by prioux** [comment]
@candicecz Added one more feature request (who am I in top bar)

**Comment by natacha-beck** [comment]
@candicecz Added a bug.

**Comment by natacha-beck** [comment]
@candicecz I am able to accept the invitation in the Dashboard (I really like the idea to have it in the Dashboard). But I am not able to accept it in the `nh_invitations` index page.

**Comment by xlecours** [comment]
@prioux "bug/feature request" added about opening a new window when switching to CBRAIN's UI.

**Comment by prioux** [comment]
@xlecours Yes, good idea

**Comment by prioux** [comment]
@candicecz UI suggestion added

**Comment by prioux** [comment]
@candicecz thirs UI suggestion (View Licenses) added

**Comment by natacha-beck** [comment]
@candicecz +1 for  `UI suggestion: do we need to repeat the links to dashboard, my account etc in the footer?`

**Comment by candicecz** [comment]
I'm still thinking about this. I think the answer will become more clear in time so I'm leaving it for now. I think once I create pagination for projects, userfiles, etc then we probably won't need it.

**Comment by prioux** [comment]
This entry logs completed bullet points as of Apr 7th.

- [x] Cannot return to project list page from MyAccount page
- [x] No error message when filling registration form incorrectly
- [x] Created a signup, was redirected to a page that does not exist (url is wrong, contains dot instead of slash)
- [x] Flash message do not render properly in the login page (e.g. when account is locked)
- [x] The project 'show' page inverts the name of the project and the name of the creator
- [x] The HBHL logo at the top link to `nh_session`, it is not a valid route. Not sure about the right link to put here.
- [x] Link to `INVITATIONS` could be only present in the toolbar if user have pending invitations.
- [x] Too much unnecessary uppercasing in the interface. The project buttons list for instance shows all the project names in uppercase; given that sometimes casing is an important carrier of information, it should respect the creator's original casing. Also, the names can often be part of API calls, so it need to be show faithfully in case the user selects them from the interface with cut-and-paste. Other example: creator name in the projects. Candice, please review all interface elements to change unnecessary uppercasing. 
- [x] Add a 'powered by CBRAIN' footer. Small and discreet; at the bottom of all pages; see main CBRAIN site for example. Use layout system to make it general (do not need to add this to each page individually)
- [x] I'd like to know who I am without having to click on 'My Account'. My username should be shown somewhere in the top bar... ?
- [x] In the Neurohub interface I am not able anymore to accept an invitation.

**Comment by MontrealSergiy** [comment]
I can try a better name for that file (Minor, about the source code) File views/nh_projects/_form_for.html.erb should be renamed. Why is there a '_for' in there, it's not like the Rails method...)

**Comment by prioux** [comment]
Just to avoid merge conflicts, I'd rather let @candicecz do changes to UI-related files, it's her domain after all.

**Comment by MontrealSergiy** [comment]
As you wish. I am sure @candicecz can do it as well (or even better),

**Comment by prioux** [comment]
Added comment about too many fles.

**Comment by MontrealSergiy** [comment]
@prioux do you want reimplement paging manually? Another option could be use some small paging library (gem) like pagy https://github.com/ddnexus/pagy , I can try if you are fine

**Comment by candicecz** [comment]
@prioux @MontrealSergiy  I'm currently working on the tables (reformatting + adding pagination). I'm working on pagination the way it currently works on CBRAIN. Let me know if I should be doing things different.

**Comment by MontrealSergiy** [comment]
@candicecz I do not mind

**Comment by prioux** [comment]
@MontrealSergiy OK after dicussions with @candicecz I think you can start investigating that 'pagy' Gem. What I want:

1) simple minimal code for pagniation of the files index page
2) only minor changes to controller and a few new buttons or links on the index page to support pagination
3) do it in a separate branch and make a PR

**Comment by prioux** [comment]
Once this works for the files index page we'll add the same functionality for the projects index page (both list and button views)

**Comment by prioux** [comment]
@candicecz : added a tiny bug on the cbrain side caused by one of your changes (title helper method)

@MontrealSergiy : added a tiny bug on the cbrain side cause by your licensing code

**Comment by MontrealSergiy** [comment]
the license bug is fixed, files are paged.

**Comment by prioux** [comment]
Added a search box bug report for @natacha-beck

**Comment by MontrealSergiy** [comment]
@prioux should I add paging to project index?

**Comment by prioux** [comment]
@MontrealSergiy Yes please, you actually anticipated what I was going to ask. But make sure you synchronize your modifications with @candicecz first so that you guys don't modify the same files at the same time.

**Comment by candicecz** [comment]
@MontrealSergiy Could you also add an input field so that the user can modify the number of files/projects to show per page?

**Comment by MontrealSergiy** [comment]
ok

**Comment by prioux** [comment]
@natacha-beck Added a bug with the invitation controller

**Comment by prioux** [comment]
**Issues closed as of Apr 15th**

- [x] We need to put a limit on the number of files shown, or implement pagination. I clicked on a project with >80K files and it took a long time to render the page. And it's useless too.
- [x] (Sergiy) Bug: the license_check callback for the CBRAIN side fails when the user switches to "no active project" (with id=all).
- [x] (Natacha) The search box is broken again. I tried 'abide' and internal exceptions were raised.
- [x] If someone tries to accept an invitation for a project which no longer exists, an exception is created. Line 90 in controller: `@nh_project = @nh_invitation.group`. A message should be shown and the invitation cancelled/deleted.

**Comment by candicecz** [comment]
**Issues closed as of Apr 16th**

- [x] The upload file button that redirect to CBRAIN's UI should open a new window/tag because there is no way for the user to come back to the NeuroHub UI. 
- [x] UI suggestion. Whemever there is a link that takes the user to CBRAIN, why not add a tiny [cb] logo after it? (we could use the small square blue-and-white [cb] logo) 
- [x] UI suggestion: do we need to repeat the links to dashboard, my account etc in the footer?
- [x] UI suggestion: On the Dashboard you will see a new `search` box, when used it will redirect to a pages with the result of the search. This page need to be improve @candicecz .
- [x] (Candice) Bug: Some neurohub changes to the title() helper is messing up the layout of the titles in the CBRAIN page (e.g. the DataProvider pages shows up as `-DataProviders`
- [x] Remove the little standalone dash in the descriptions of projects that have no descriptions (button view)

**Comment by prioux** [comment]
Wow, quite a large set of changes @candicecz !

**Comment by natacha-beck** [comment]
**Issues closed as of Apr 20th**

Enter NeuroHub bugs/limitations below as a checklist. Checkboxes are created with dash, space, square bracket, space, square bracket, space (- [ ] Text).

- [x] (Pierre) No error message is shown when the user has invalid username or password in the signin page. Wasn't there a place for flash messages there before?
- [x] (Pierre) (Minor, about the source code) File views/nh_projects/_form_for.html.erb should be renamed. Why is there a '_for' in there, it's not like the Rails method...
- [x] (Pierre) Why does My Account show the Zenodo sandbox token but not the official one?
- [x] (Natacha) BUG: the search function is totally inefficient; if someone search for something that returns lots of results, all the result objects are built before being limited to 20. This occurs at this line: `@files    = @results[:files][0,@limit]` which is an array operation instead of an active record limit. E.g. in the production DB if an admin search for 'a', the code will reconstruct 286,000 objects before selecting the first 20 and discarding the rest. (I fixed this -- PR)
- [x] (Natacha) Search crash on my dev environment: no such method `keep_if` in neurohub_portal_controller line 94. (I fixed this -- PR)

**Comment by MontrealSergiy** [comment]
@prioux @natacha-beck @candicecz I recall on previous meeting we were suggested to add more items to neurohub news. Not sure who was assigned. Perhaps we can add something (may be check first with diana, samir or/and JB )  "New features added - upload, connecting folders on users personal or supercomputer disc space with ssh, paging and search. Neurohub is feature complete! After extensive testing and optimization Neurohub will be open for organization wide use.

**Comment by MontrealSergiy** [comment]
@nbeck How task search work? if I (sboroday) search for word 'file' I get bunch of task yet trying searching by a task name fragment (niak) brings nothing

**Comment by MontrealSergiy** [comment]
@prioux  Not sure why  "Pagination defaults to 20 even if there are less than 20 items." is a bug, but to keep everybody happy, may be I can hide pagination controls from small pages?

**Comment by candicecz** [comment]
**Issues closed as of Apr 22nd**

- [x] (Candice) With the new licensing stuff, I added a link to 'View Licenses' at the top of project, but I put it such that only the project's maintainer can see the link and click on it. The link should work for any members of the project, though, so feel free to put it elsewhere.
- [x] In my account page, it will be useful to have a link to CBRAIN for all the User tasks and files.
- [x] (Candice) When we have pagination it will be useful to know the total number if items (like we have in CBRAIN)
- [x] On `nh_projects` index page we sometimes have the name of the maintainer in blue or in grey but both are link. 
- [x] UI issue in index of project, I am not able to see anymore the number of items setting (repored by Natacha)

**Comment by MontrealSergiy** [comment]
regarding bug "Acces to index of files of a Public project " - on private projects file index might differ as well. yet unavailable files cannot be downloaded, and error message is displayed if user click on it

**Comment by MontrealSergiy** [comment]
@prioux @xlecours who should be able to add storage/dp to neurohub projects? just any user (as it is now) or only editors?

**Comment by prioux** [comment]
@MontrealSergiy only the creator or the editors

**Comment by prioux** [comment]
Well, maybe not... ?

**Comment by natacha-beck** [comment]
For the following point: 

> Acces to index of files of a Public project do not ... 

@MontrealSergiy after discussion with @prioux everything is ok. We know why the list is different and that is fine like that. 
In NH every files of the project are shown and in CBRAIN only the one on available DataProvider are display on the index page.

**Comment by MontrealSergiy** [comment]
Well, since non-editors can add files, why not storage. It is then a bit misleading that non-editing contributor do not see add storage button if project is non-editing. Then hiding add storage button on non-editable projects makes no sense. It makes users think that neurohub prevents non-editors from adding storage

**Comment by MontrealSergiy** [comment]
@candicecz if time check how Microsoft Edge is rendering thing (especially navigation bar/main menu). Adding to buglist

**Comment by MontrealSergiy** [comment]
@prioux maybe remove 'select project' from the new project dropdown? When selected,  it adds storage to the 'personal' project which is not in neurohub (added to buglist).

**Comment by prioux** [comment]
@MontrealSergiy Do you mean in "add storage" in many of your comments above? I could not figure out what you mean until I realized maybe you mis typed your comments. E.g. you wrote:

```
(Pierre) in *add project form* user can set select project field to 'select project' and will create a storage to his personal project (like sboroday).
```

but I think you mean "add storage form" ?

**Comment by MontrealSergiy** [comment]
I meant add project form

**Comment by candicecz** [comment]
** Issues closed as of Apr 29th **
- [x] (Pierre) Upload files: allow user to pick a file type (CANCELLED: no time)
- [x] (Pierre) Upload files: allow users to select the main NeuroHub DP I set up
- [x] (Pierre) Confirm dialog for 'deconfigure storage'.
- [x] (Candice) "Lost Password?" is NYI. I suggest redirecting to CBRAIN (with a note to that effect)
- [x] Update description of public project.
- [x] Update description of storage options(test configuration, deconfigure, autoregister) in app/views/nh_storages/show.
- [x] Acces to index of files of a Public project do not give the same result in CBRAIN and in NH. 
Case: With a Normal user accessing a public project without being a member. In CBRAIN I found files present on accessible DP only, in NH I found all the files even if I do not have access to the DP. Example with the my standard user, and the project number `6000` in NH I get 3 files and in CBRAIN I get only 2 files. Before we get 3 files in CBRAIN too if I am right. (Serge: the files list also differ on  on private projects, yet error is displayed if user tries access file page)  
- [x] (Pierre) in add storage form user can set select project field to 'select project' and will create a storage to his personal project (like sboroday). 
- [x] (Candice) check MS Edge if you can, nav bar does not look great on older, pre-chrome Edge ( tested with version 44)

**Comment by natacha-beck** [comment]
> user should be able only to add storage to a project if he is editor or maintainer at the least, remove irrelevant projects from the create new storage forms' project dropdown. IF I am wrong and it is fine for any contributor to add project storage, put back the add storage button to non-editable projects. (Natacha note: I am able to add a DP to a PUBLIC project via CBRAIN, when I use a user (SiteManager) that is a member of this group but not an Editor. I should not be able to do that.)

This seems fine and work as exxpected:

- The option are not available in NH. 
- I am not able to do that in CBRAIN except with a SiteManager for Project own by one of the member of my Site.

**Comment by natacha-beck** [comment]
For the point about Licence, we assume that only Maintainer of the project can add it.

**Comment by prioux** [comment]
I think we can close this now, as the remaining issues are tracked separately.
